### ISSUE TITLE
Framework Integrations

### ISSUE THREAD

**Issue by alexander-schranz** [schranz-search/schranz-search#113]
## Symfony

 - [x] Init Bundle #112
 - [x] Adapter Integration #112
 - [x] Schema Integration #135
 - [x] Engine Integration #135
 - [x] EngineRegistry Integration #140
 - [x] Prefix config #142
 - [x] Create & Drop CLI Commands #143
 - [ ] ~~Move config under seal~~
 - [x] Publish Package

## Laravel

 - [x] Init Module #136
 - [x] Adapter Integration #136
 - [x] Schema Integration #136
 - [x] Engine Integration #136
 - [x] EngineRegistry Integration #136
 - [x] Prefix config #142
 - [x] Create & Drop CLI Commands #143
 - [ ] ~~Move config under seal~~
 - [x] Publish Package
 - [ ] ~~Scout Integration?~~ moved to an own issue: https://github.com/schranz-search/schranz-search/issues/148

## Spiral

 - [x] Init Package #141
 - [x] Adapter Integration #141
 - [x] Schema Integration #141
 - [x] Engine Integration #141
 - [x] EngineRegistry Integration #141
 - [x] Prefix config #142
 - [x] Create & Drop CLI Commands #143
 - [ ] ~~Move config under seal~~
 - [x] Publish Package
 
----

Not tackling for the release:

 - Mezzio
 - Laminas
