### ISSUE TITLE
[New package] ODM/ORM based Datamapping to Document classes

### ISSUE THREAD

**Issue by alexander-schranz** [schranz-search/schranz-search#81]
The current abstraction requires json like arrays to be indexed and return that indexes. There should be in future another package build on top of `seal` package which will do mapping from `PHP Classes` so `Document Object` to this array and back to it.

So the `seal` package will be something like what in doctrine is `doctrine/dbal` and the `odm` or whatever we will call it will be what `doctrine/orm` is.

A ODM Impelmentaiton could look like this:

```php
<?php

use Schranz\Search\SEAL\Schema\Field;
use Schranz\Search\SEAL\Schema\Index;

#[Index(name: 'news')]
class News {
    #[Field\IdentifierField('id')]
    private string $id;
    
    #[Field\TextField('title')]
    private string $title;
    
    #[Field\TypedField('header', 'type', [
        'image' => [
            'media' => new Field\IntegerField('media'),
        ],
        'video' => [
            'media' => new Field\TextField('media', searchable: false),
        ],
    ])]
    private array $header;
    
    // ...
}
```

# Open Points

 - [ ] `array` <-> `object` mapping: Find the best way to map array to object maybe look at following components:
    - [Symfony Normalizer and Denormalizer](https://symfony.com/doc/current/components/serializer.html)
    - [Symfony PropertyAccessor](https://symfony.com/doc/current/components/property_access.html)
    - [Symfony ObjectMapper](https://github.com/symfony/symfony/pull/51741) (think does not support array to object)
    - [Doctrine Object Instantiator](https://github.com/doctrine/instantiator)
    - [thephpleague/object-mapper](https://github.com/thephpleague/object-mapper)
    - [JanePHP](https://github.com/janephp/janephp)
    - [CuyZ/Valinor](https://github.com/CuyZ/Valinor)
- [ ] Check what we can keep in mind from @Pierstoval feedback here: https://github.com/PHP-CMSIG/search/discussions/512 

# ToDo

- [ ] Own seal-attributes package which contains the Attributes and AttributeSchemaLoader based on [SchemaLoaderInterface](https://github.com/PHP-CMSIG/search/blob/0.7/packages/seal/src/Schema/Loader/LoaderInterface.php)
- [ ] Own seal-odm package with ObjectManager which wraps the EngineInterface and maps array result to the object and back.
- [ ] Doctrine Implementation Objectmapper? from Entity to our own ODM Documents
